name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

template: |
  ## What’s Changed
  https://github.com/projectblacklight/spotlight/compare/v($PREVIOUS_TAG)...v($NEXT_PATCH_VERSION)

  $CHANGES

  THANKS FOR THESE HELPFUL MESSAGES!!!
  $CONTRIBUTORS
