name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

template: |
  ## 👀📝 For Release Drafter (DELETE ME BEFORE PUBLISHING)
  - [ ] Review changes: https://github.com/camillevilla/release-drafter-test/compare/$PREVIOUS_TAG...master
  - [ ] Is this a major, minor, or patch release?
    - [ ] PR for bumping version number
    - [ ] Update release notes title 
  - [ ] Delete this checklist
  - [ ] Publish GitHub release
  - [ ] Push release to RubyGems
  - [ ] Post to Slack channel

  ## What’s Changed

  https://github.com/camillevilla/release-drafter-test/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION

  $CHANGES

  Thank you to all of the contributors for this release!!! 🥇
  $CONTRIBUTORS
